name: ridemate_ai
description: RideMate AI Flutter MVP with rider and driver role flows.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  google_fonts: ^6.2.1
  flutter_map: ^8.3.1
  latlong2: ^0.9.1
  geolocator: ^14.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/rickshaw.png
    - assets/images/car.png
    - assets/images/auto_rickshaw.jpg
    - assets/images/blue_car.jpg
